# Generated by Django 5.0.1 on 2024-01-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desk_id', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
