# Generated by Django 5.0 on 2024-01-30 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desk_id', models.CharField(max_length=200)),
                ('desk_description', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('city_name', models.CharField(max_length=100)),
                ('availability', models.BooleanField(default=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('post_code', models.IntegerField(default=0)),
                ('desk_number', models.IntegerField(default=0)),
                ('ergonomic_chair_number', models.IntegerField(default=0)),
                ('desk_monitor_number', models.IntegerField(default=0)),
            ],
        ),
    ]
