# Generated by Django 5.0 on 2024-01-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desk_id', models.CharField(max_length=200)),
                ('desk_description', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('availability', models.BooleanField(default=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('user_ratings', models.FloatField(default=0.0)),
                ('frequency_of_bookings', models.IntegerField(default=0)),
                ('feedback', models.TextField()),
                ('accuracy_of_description', models.FloatField(default=0.0)),
            ],
        ),
    ]
