# Generated by Django 5.0 on 2024-02-22 12:50

import hotdesk.custom_date_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desk',
            name='date_times',
            field=hotdesk.custom_date_field.DateArrayField(blank=True, null=True),
        ),
    ]
