# Generated by Django 5.0 on 2024-02-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desk',
            name='solid_username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
