# Generated by Django 5.0 on 2024-01-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desk',
            name='feedback',
            field=models.FloatField(default=0.0),
        ),
    ]
