# Generated by Django 5.0 on 2024-01-31 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desk',
            name='post_code',
            field=models.CharField(default='00000', max_length=100),
        ),
    ]
