# Generated by Django 5.0 on 2024-01-31 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotdesk', '0002_alter_desk_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desk',
            name='post_code',
            field=models.CharField(default='00000', max_length=5),
        ),
    ]
