# Generated by Django 5.0 on 2024-01-31 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotdesk', '0003_alter_desk_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desk',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='desk',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
