# Generated by Django 5.0 on 2024-02-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotdesk', '0004_alter_desk_end_time_alter_desk_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedDesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desk_id', models.CharField(max_length=200)),
                ('desk_description', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('city_name', models.CharField(max_length=100)),
                ('availability', models.BooleanField(default=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('post_code', models.CharField(default='00000', max_length=5)),
                ('desk_number', models.IntegerField(default=0)),
                ('ergonomic_chair_number', models.IntegerField(default=0)),
                ('desk_monitor_number', models.IntegerField(default=0)),
            ],
        ),
    ]
