# Generated by Django 5.0 on 2024-02-05 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotdesk', '0005_bookeddesk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookedDesk',
        ),
    ]
