# Generated by Django 5.0 on 2024-02-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotdesk', '0006_delete_bookeddesk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desk',
            name='availability',
            field=models.BooleanField(),
        ),
    ]
