# Generated by Django 5.0 on 2024-02-06 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotdesk', '0008_alter_desk_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desk',
            name='availability',
        ),
    ]
