# Generated by Django 5.0 on 2024-02-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotdesk', '0009_remove_desk_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='desk',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
